package sandboxtest

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// ErrUnsupported is returned when the running platform cannot host a
// FakeBinary. Tests that hit this error should `t.Skip` rather than
// fail, since the limitation is the platform's, not the helper's.
var ErrUnsupported = errors.New("sandboxtest: FakeBinary unavailable on this platform")

// Recording is the JSON shape a [FakeBinary] writes to disk when
// RecordPath is set. Tests read it back with [LoadRecording] to
// assert on the argv, env, and cwd the runtime actually passed to
// the subprocess.
//
// Stdin capture is not yet supported and is omitted from v1; the
// fake binary script can read stdin but cannot record it without a
// shell-quoting hazard around the embedded Python script body.
type Recording struct {
	Argv []string `json:"argv"`
	Env  []string `json:"env"`
	Cwd  string   `json:"cwd"`
}

// FakeBinary is a configured scripted executable. Call [Write] to
// materialize it on disk; the returned path is suitable for use in a
// [sandbox.SpawnEnvelope]'s Program field.
//
// Cross-platform note: v1 only supports POSIX hosts (sh on PATH).
// The Windows port lands in a follow-up; tests on Windows should
// detect [ErrUnsupported] from [Write] and skip, or substitute a
// [RecordingExecutor] which is platform-agnostic.
type FakeBinary struct {
	// Stdout is written verbatim to stdout when the binary runs.
	Stdout string

	// Stderr is written verbatim to stderr when the binary runs.
	Stderr string

	// ExitCode is the exit status the binary terminates with.
	ExitCode int

	// RecordPath, when non-empty, names a file the binary writes a
	// JSON [Recording] to. Tests use [LoadRecording] to read it back.
	RecordPath string
}

// Write materializes a fake-binary script at <dir>/<name>. The file
// is marked executable. Returns the absolute path the test passes
// as the [sandbox.SpawnEnvelope]'s Program field.
//
// Returns [ErrUnsupported] on Windows. The test is responsible for
// skipping on that platform.
func (f FakeBinary) Write(dir, name string) (string, error) {
	if runtime.GOOS == "windows" {
		return "", ErrUnsupported
	}
	path := filepath.Join(dir, name)
	body := f.renderShellScript()
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return "", err
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	return abs, nil
}

// renderShellScript produces the POSIX shell body of a FakeBinary.
// Recording uses python3 (universally available on macOS/Linux test
// runners) when CaptureStdin is true, since shell quoting of
// arbitrary stdin bytes into a JSON record is fragile.
func (f FakeBinary) renderShellScript() string {
	var b strings.Builder
	fmt.Fprintln(&b, "#!/bin/sh")
	fmt.Fprintln(&b, "# fake-binary script generated by sandboxtest.FakeBinary")
	if f.RecordPath != "" {
		fmt.Fprintln(&b, "python3 - \"$@\" <<'PYEOF'")
		fmt.Fprintln(&b, "import json, os, sys")
		fmt.Fprintf(&b, "rec = {\n")
		fmt.Fprintf(&b, "  'argv': sys.argv,\n")
		fmt.Fprintf(&b, "  'env': [k+'='+v for k,v in os.environ.items()],\n")
		fmt.Fprintf(&b, "  'cwd': os.getcwd(),\n")
		fmt.Fprintln(&b, "}")
		fmt.Fprintf(&b, "with open(%q, 'w') as fp:\n", f.RecordPath)
		fmt.Fprintln(&b, "    json.dump(rec, fp)")
		fmt.Fprintln(&b, "PYEOF")
	}
	if f.Stdout != "" {
		// Use printf '%s' for byte-exact emission without trailing newline.
		fmt.Fprintf(&b, "printf '%%s' %s\n", shellQuote(f.Stdout))
	}
	if f.Stderr != "" {
		fmt.Fprintf(&b, "printf '%%s' %s 1>&2\n", shellQuote(f.Stderr))
	}
	if f.ExitCode != 0 {
		fmt.Fprintf(&b, "exit %d\n", f.ExitCode)
	}
	return b.String()
}

// shellQuote produces a POSIX-shell-safe single-quoted string for s.
// Embedded single quotes are escaped via the canonical
// `'...'\''...'` pattern.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// LoadRecording reads a Recording file produced by a FakeBinary
// whose RecordPath was set.
func LoadRecording(path string) (*Recording, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var rec Recording
	if err := json.Unmarshal(body, &rec); err != nil {
		return nil, fmt.Errorf("decode recording %s: %w", path, err)
	}
	return &rec, nil
}

// EnvHas reports whether the recorded env contains the given KEY=VALUE
// pair. Convenient for asserting the runtime injected the env keys
// the manifest declared.
func (r *Recording) EnvHas(key, value string) bool {
	if r == nil {
		return false
	}
	want := key + "=" + value
	for _, kv := range r.Env {
		if kv == want {
			return true
		}
	}
	return false
}

// EnvKeys returns just the keys (left of `=`) the recorded env held.
// Use this to assert the env-passthrough policy was honored
// (no leaked keys).
func (r *Recording) EnvKeys() []string {
	if r == nil {
		return nil
	}
	out := make([]string, 0, len(r.Env))
	for _, kv := range r.Env {
		eq := strings.IndexByte(kv, '=')
		if eq < 0 {
			out = append(out, kv)
			continue
		}
		out = append(out, kv[:eq])
	}
	return out
}
