package main

import (
	"context"
	"crypto/ecdh"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"sync"
	"time"

	"github.com/ALRubinger/aileron/internal/connector"
	"github.com/ALRubinger/aileron/internal/crypto"
	"github.com/ALRubinger/aileron/internal/enclave"
	"github.com/ALRubinger/aileron/internal/source"
)

const (
	enclaveSessionTTL     = 30 * time.Minute
	requestAuthMaxSkew    = 5 * time.Minute
	requestAuthNonceBytes = 32
)

type enclaveServer struct {
	log                   *slog.Logger
	registry              *connector.Registry
	sourceRegistry        *source.Registry
	provider              string
	mu                    sync.Mutex
	enclaveKey            *ecdh.PrivateKey
	sessionKey            []byte
	requestAuthKey        []byte
	grantCapabilityKey    []byte
	sessionID             string
	expiresAt             time.Time
	seenNonces            map[string]time.Time
	usedGrantCapabilities map[string]time.Time
	keks                  *kekStore
	escrow                *escrowStore
}

func newEnclaveServer(log *slog.Logger, registry *connector.Registry, sourceReg *source.Registry, provider, dataDir string) (*enclaveServer, error) {
	escrow, err := newEscrowStore(dataDir)
	if err != nil {
		return nil, fmt.Errorf("initializing escrow store: %w", err)
	}
	return &enclaveServer{
		log:                   log,
		registry:              registry,
		sourceRegistry:        sourceReg,
		provider:              provider,
		seenNonces:            make(map[string]time.Time),
		usedGrantCapabilities: make(map[string]time.Time),
		keks:                  newKEKStore(),
		escrow:                escrow,
	}, nil
}

func (s *enclaveServer) registerRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /attest", s.handleAttest)
	mux.HandleFunc("POST /session", s.handleSession)
	mux.HandleFunc("POST /kek", s.handleTransmitKEK)
	mux.HandleFunc("POST /oauth/exchange", s.handleOAuthExchange)
	mux.HandleFunc("POST /execute", s.handleExecute)
	mux.HandleFunc("POST /escrow", s.handleEscrowStore)
	mux.HandleFunc("POST /escrow/list", s.handleEscrowList)
	mux.HandleFunc("POST /escrow/revoke", s.handleEscrowRevoke)
	mux.HandleFunc("POST /source/execute", s.handleSourceExecute)
	mux.HandleFunc("GET /health", s.handleHealth)
}

func (s *enclaveServer) handleAttest(w http.ResponseWriter, r *http.Request) {
	var req enclave.AttestationRequest
	if err := decodeJSON(r, &req); err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}

	// Generate ephemeral ECDH key pair.
	priv, err := ecdh.P256().GenerateKey(rand.Reader)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "generating key pair")
		return
	}

	s.mu.Lock()
	s.enclaveKey = priv
	s.mu.Unlock()

	// Bind the ECDH public key to the attestation token by including its
	// SHA-256 hash as a nonce in eat_nonce. The verifier (server and browser)
	// can independently compute SHA-256(public_key) and confirm it appears
	// in the signed token, proving the key was generated by this enclave.
	pubkeyHash := sha256.Sum256(priv.PublicKey().Bytes())
	nonces := []string{
		base64.RawURLEncoding.EncodeToString(req.Nonce),
		base64.RawURLEncoding.EncodeToString(pubkeyHash[:]),
	}

	// Get attestation token with nonces bound.
	token, err := fetchAttestationToken(s.provider, req.Audience, nonces)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "fetching attestation token: "+err.Error())
		return
	}

	writeJSON(w, http.StatusOK, enclave.AttestationResponse{
		Token:     token,
		PublicKey: priv.PublicKey().Bytes(),
	})
}

func (s *enclaveServer) handleSession(w http.ResponseWriter, r *http.Request) {
	var req enclave.SessionRequest
	if err := decodeJSON(r, &req); err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if s.enclaveKey == nil {
		writeErr(w, http.StatusPreconditionFailed, "attestation required first")
		return
	}

	hostPub, err := ecdh.P256().NewPublicKey(req.PublicKey)
	if err != nil {
		writeErr(w, http.StatusBadRequest, "invalid public key: "+err.Error())
		return
	}

	raw, err := s.enclaveKey.ECDH(hostPub)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "ECDH exchange failed")
		return
	}
	h := sha256.Sum256(raw)

	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		writeErr(w, http.StatusInternalServerError, "generating session ID")
		return
	}

	requestAuthKey := make([]byte, requestAuthNonceBytes)
	if _, err := rand.Read(requestAuthKey); err != nil {
		writeErr(w, http.StatusInternalServerError, "generating request auth key")
		return
	}
	grantCapabilityKey := copyBytes(req.GrantCapabilityKey)
	if len(grantCapabilityKey) == 0 {
		grantCapabilityKey = make([]byte, requestAuthNonceBytes)
		if _, err := rand.Read(grantCapabilityKey); err != nil {
			writeErr(w, http.StatusInternalServerError, "generating grant capability key")
			return
		}
	}

	// Zero previous session material only after the new session is ready.
	zeroBytes(s.sessionKey)
	zeroBytes(s.requestAuthKey)
	zeroBytes(s.grantCapabilityKey)

	s.sessionKey = h[:]
	s.requestAuthKey = requestAuthKey
	s.grantCapabilityKey = grantCapabilityKey
	s.expiresAt = time.Now().Add(enclaveSessionTTL)
	s.sessionID = hex.EncodeToString(b)
	clear(s.seenNonces)
	clear(s.usedGrantCapabilities)

	writeJSON(w, http.StatusOK, enclave.SessionResponse{
		SessionID:          s.sessionID,
		ExpiresAt:          s.expiresAt.Format(time.RFC3339),
		RequestAuthKey:     copyBytes(s.requestAuthKey),
		GrantCapabilityKey: copyBytes(s.grantCapabilityKey),
	})
}

func (s *enclaveServer) handleTransmitKEK(w http.ResponseWriter, r *http.Request) {
	var req enclave.TransmitKEKRequest
	authKey, err := s.decodeAuthenticatedJSON(w, r, &req)
	if err != nil {
		if err == errResponseWritten {
			return
		}
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	zeroBytes(authKey)

	s.mu.Lock()
	sessionKey := copyBytes(s.sessionKey)
	s.mu.Unlock()

	if sessionKey == nil {
		writeErr(w, http.StatusPreconditionFailed, "no active session")
		return
	}
	defer zeroBytes(sessionKey)

	// Decrypt KEK using session key.
	kek, err := crypto.Decrypt(req.EncryptedKEK, sessionKey)
	if err != nil {
		writeErr(w, http.StatusBadRequest, "KEK decryption failed: "+err.Error())
		return
	}

	s.keks.Store(req.UserID, kek)
	zeroBytes(kek)
	s.log.Info("KEK stored for user", "user_id", req.UserID)

	writeJSON(w, http.StatusOK, enclave.TransmitKEKResponse{Stored: true})
}

func (s *enclaveServer) handleOAuthExchange(w http.ResponseWriter, r *http.Request) {
	var req enclave.OAuthExchangeRequest
	authKey, err := s.decodeAuthenticatedJSON(w, r, &req)
	if err != nil {
		if err == errResponseWritten {
			return
		}
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	zeroBytes(authKey)

	// Get user's KEK.
	kek, err := s.keks.Get(req.UserID)
	if err != nil {
		writeErr(w, http.StatusPreconditionFailed, "no KEK for user: "+err.Error())
		return
	}
	defer zeroBytes(kek)

	// Exchange authorization code for tokens.
	oauthResult, err := doOAuthExchange(r.Context(), req)
	if err != nil {
		writeErr(w, http.StatusBadGateway, "OAuth exchange failed: "+err.Error())
		return
	}
	defer zeroBytes(oauthResult.tokenJSON)

	// Fetch user email.
	email, _ := doFetchEmail(r.Context(), req.UserInfoEndpoint, oauthResult.accessToken)

	// Encrypt token JSON with user's KEK.
	encrypted, err := crypto.Encrypt(oauthResult.tokenJSON, kek)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "encrypting token: "+err.Error())
		return
	}

	writeJSON(w, http.StatusOK, enclave.OAuthExchangeResponse{
		EncryptedToken: encrypted,
		Email:          email,
		TokenType:      oauthResult.tokenType,
		ExternalUserID: oauthResult.externalUserID,
		ExternalTeamID: oauthResult.externalTeamID,
	})
}

func (s *enclaveServer) handleExecute(w http.ResponseWriter, r *http.Request) {
	var req enclave.ExecuteRequest
	authKey, err := s.decodeAuthenticatedJSON(w, r, &req)
	if err != nil {
		if err == errResponseWritten {
			return
		}
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	defer zeroBytes(authKey)
	if !enclave.VerifyExecuteCapability(authKey, req) {
		writeErr(w, http.StatusForbidden, "invalid grant capability")
		return
	}
	if err := s.verifyIssuedExecuteCapability(req); err != nil {
		writeErr(w, http.StatusForbidden, err.Error())
		return
	}

	// Resolve credential.
	var credential []byte
	if req.EscrowID != "" {
		cred, err := s.escrow.GetForExecute(req)
		if err != nil {
			writeEscrowErr(w, err)
			return
		}
		credential = cred
	} else {
		// Decrypt credential with user's KEK.
		kek, err := s.keks.Get(req.UserID)
		if err != nil {
			writeErr(w, http.StatusPreconditionFailed, "no KEK for user: "+err.Error())
			return
		}
		plain, decErr := crypto.Decrypt(req.EncryptedCredential, kek)
		zeroBytes(kek)
		if decErr != nil {
			writeErr(w, http.StatusBadRequest, "decryption failed: "+decErr.Error())
			return
		}
		credential = plain
	}
	defer zeroBytes(credential)

	// Resolve connector.
	connType, connProvider := resolveConnectorID(req.ConnectorID)
	conn, ok := s.registry.Get(r.Context(), connType, connProvider)
	if !ok {
		writeErr(w, http.StatusBadRequest, "no connector for "+req.ConnectorID)
		return
	}

	// Execute.
	result, err := conn.Execute(r.Context(), connector.ExecutionRequest{
		GrantID:    req.GrantID,
		IntentID:   req.IntentID,
		ActionType: req.ActionType,
		Parameters: req.Parameters,
		Credential: &connector.InjectedCredential{
			Type:  req.CredentialType,
			Value: credential,
		},
	})
	if err != nil {
		writeJSON(w, http.StatusOK, enclave.ExecuteResponse{
			RequestID: req.RequestID,
			Status:    "failed",
			Error:     err.Error(),
		})
		return
	}

	status := "succeeded"
	if result.Status == connector.ExecutionStatusFailed {
		status = "failed"
	}

	writeJSON(w, http.StatusOK, enclave.ExecuteResponse{
		RequestID:  req.RequestID,
		Status:     status,
		Output:     result.Output,
		ReceiptRef: result.ReceiptRef,
		Error:      result.Error,
	})
}

func (s *enclaveServer) handleEscrowStore(w http.ResponseWriter, r *http.Request) {
	var req enclave.EscrowStoreRequest
	authKey, err := s.decodeAuthenticatedJSON(w, r, &req)
	if err != nil {
		if err == errResponseWritten {
			return
		}
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	defer zeroBytes(authKey)
	if !enclave.VerifyEscrowStoreCapability(authKey, req) {
		writeErr(w, http.StatusForbidden, "invalid grant capability")
		return
	}
	if req.UserID == "" {
		writeErr(w, http.StatusBadRequest, "user_id required")
		return
	}
	if req.GrantID == "" {
		writeErr(w, http.StatusBadRequest, "grant_id required")
		return
	}
	if req.VaultPath == "" {
		writeErr(w, http.StatusBadRequest, "vault_path required")
		return
	}
	if req.Provider == "" {
		writeErr(w, http.StatusBadRequest, "provider required")
		return
	}
	if req.CredentialType == "" {
		writeErr(w, http.StatusBadRequest, "credential_type required")
		return
	}
	expiresAt, err := time.Parse(time.RFC3339, req.ExpiresAt)
	if err != nil {
		writeErr(w, http.StatusBadRequest, "invalid expires_at: "+err.Error())
		return
	}
	if err := s.verifyIssuedEscrowCapability(req); err != nil {
		writeErr(w, http.StatusForbidden, err.Error())
		return
	}

	// Decrypt credential with user's KEK.
	kek, err := s.keks.Get(req.UserID)
	if err != nil {
		writeErr(w, http.StatusPreconditionFailed, "no KEK for user: "+err.Error())
		return
	}

	plaintext, err := crypto.Decrypt(req.EncryptedCredential, kek)
	zeroBytes(kek)
	if err != nil {
		writeErr(w, http.StatusBadRequest, "decryption failed: "+err.Error())
		return
	}

	id := s.escrow.Store(req, plaintext, expiresAt)
	writeJSON(w, http.StatusOK, enclave.EscrowStoreResponse{EscrowID: id})
}

func (s *enclaveServer) handleEscrowList(w http.ResponseWriter, r *http.Request) {
	_, authKey, ok := s.requireAuthenticatedRequest(w, r)
	if !ok {
		return
	}
	zeroBytes(authKey)

	entries := s.escrow.List()
	writeJSON(w, http.StatusOK, enclave.EscrowListResponse{Entries: entries})
}

func (s *enclaveServer) handleEscrowRevoke(w http.ResponseWriter, r *http.Request) {
	var req enclave.EscrowRevokeRequest
	authKey, err := s.decodeAuthenticatedJSON(w, r, &req)
	if err != nil {
		if err == errResponseWritten {
			return
		}
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	zeroBytes(authKey)

	if err := s.escrow.Revoke(req.EscrowID, req.GrantID); err != nil {
		writeErr(w, http.StatusNotFound, err.Error())
		return
	}

	w.WriteHeader(http.StatusNoContent)
}

func (s *enclaveServer) handleSourceExecute(w http.ResponseWriter, r *http.Request) {
	var req enclave.SourceExecuteRequest
	authKey, err := s.decodeAuthenticatedJSON(w, r, &req)
	if err != nil {
		if err == errResponseWritten {
			return
		}
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	defer zeroBytes(authKey)
	if !enclave.VerifySourceExecuteCapability(authKey, req) {
		writeErr(w, http.StatusForbidden, "invalid grant capability")
		return
	}

	// Resolve credential from escrow — plaintext stays inside the enclave.
	credential, err := s.escrow.GetForSource(req)
	if err != nil {
		writeEscrowErr(w, err)
		return
	}

	// Inject a TokenSaver that updates the escrowed credential when an
	// OAuth token is refreshed. This keeps the escrow fresh without
	// involving the host.
	escrowID := req.EscrowID
	ctx := source.WithTokenSaver(r.Context(), func(_ context.Context, newToken []byte) error {
		s.log.Info("updating escrowed credential after token refresh",
			"escrow_id", escrowID,
			"tool", req.Tool,
		)
		return s.escrow.Update(escrowID, newToken)
	})

	result, execErr := s.sourceRegistry.ExecuteTool(ctx, req.Tool, req.Params, credential)

	resp := enclave.SourceExecuteResponse{}
	if execErr != nil {
		resp.Error = execErr.Error()
	} else if result != nil {
		resultJSON, marshalErr := json.Marshal(result)
		if marshalErr != nil {
			writeErr(w, http.StatusInternalServerError, "marshaling result: "+marshalErr.Error())
			return
		}
		resp.Result = resultJSON
	}
	writeJSON(w, http.StatusOK, resp)
}

func (s *enclaveServer) handleHealth(w http.ResponseWriter, _ *http.Request) {
	s.mu.Lock()
	hasSession := s.sessionKey != nil && time.Now().Before(s.expiresAt)
	s.mu.Unlock()

	writeJSON(w, http.StatusOK, map[string]any{
		"status":         "ok",
		"provider":       s.provider,
		"session_active": hasSession,
	})
}

func (s *enclaveServer) verifyIssuedEscrowCapability(req enclave.EscrowStoreRequest) error {
	if req.IssuedCapability == nil {
		return fmt.Errorf("missing issued grant capability")
	}
	key := s.grantSigningKey()
	defer zeroBytes(key)
	if len(key) == 0 {
		return fmt.Errorf("grant capability signing key unavailable")
	}
	expected := enclave.EscrowStoreGrantCapability(req, req.IssuedCapability.Capability.Nonce)
	if !enclave.VerifySignedGrantCapability(key, req.IssuedCapability, expected) {
		return fmt.Errorf("invalid issued grant capability")
	}
	return verifyCapabilityExpiry(req.IssuedCapability)
}

func (s *enclaveServer) verifyIssuedExecuteCapability(req enclave.ExecuteRequest) error {
	if req.IssuedCapability == nil {
		return fmt.Errorf("missing issued grant capability")
	}
	key := s.grantSigningKey()
	defer zeroBytes(key)
	if len(key) == 0 {
		return fmt.Errorf("grant capability signing key unavailable")
	}
	expected := enclave.IssuedExecuteGrantCapability(req, req.IssuedCapability.Capability.Nonce, req.IssuedCapability.Capability.ExpiresAt)
	if !enclave.VerifySignedGrantCapability(key, req.IssuedCapability, expected) {
		return fmt.Errorf("invalid issued grant capability")
	}
	if err := verifyCapabilityExpiry(req.IssuedCapability); err != nil {
		return err
	}
	if !s.consumeIssuedCapability(req.IssuedCapability) {
		return fmt.Errorf("replayed issued grant capability")
	}
	return nil
}

func (s *enclaveServer) grantSigningKey() []byte {
	s.mu.Lock()
	defer s.mu.Unlock()
	return copyBytes(s.grantCapabilityKey)
}

func (s *enclaveServer) consumeIssuedCapability(capability *enclave.SignedGrantCapability) bool {
	key := capabilityReplayKey(capability)
	now := time.Now()
	s.mu.Lock()
	defer s.mu.Unlock()
	pruneSeenNonces(s.usedGrantCapabilities, now.Add(-enclaveSessionTTL))
	if _, ok := s.usedGrantCapabilities[key]; ok {
		return false
	}
	s.usedGrantCapabilities[key] = now
	return true
}

func capabilityReplayKey(capability *enclave.SignedGrantCapability) string {
	if capability == nil {
		return ""
	}
	return capability.Signature
}

func verifyCapabilityExpiry(capability *enclave.SignedGrantCapability) error {
	expiresAt := capability.Capability.ExpiresAt
	if expiresAt == "" {
		return fmt.Errorf("issued grant capability has no expiry")
	}
	expiry, err := time.Parse(time.RFC3339, expiresAt)
	if err != nil {
		return fmt.Errorf("invalid issued grant capability expiry")
	}
	if !time.Now().Before(expiry) {
		return fmt.Errorf("expired issued grant capability")
	}
	return nil
}

func (s *enclaveServer) decodeAuthenticatedJSON(w http.ResponseWriter, r *http.Request, v any) ([]byte, error) {
	body, authKey, ok := s.requireAuthenticatedRequest(w, r)
	if !ok {
		return nil, errResponseWritten
	}
	if err := json.Unmarshal(body, v); err != nil {
		zeroBytes(authKey)
		return nil, err
	}
	return authKey, nil
}

var errResponseWritten = fmt.Errorf("response already written")

func (s *enclaveServer) requireAuthenticatedRequest(w http.ResponseWriter, r *http.Request) ([]byte, []byte, bool) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		writeErr(w, http.StatusBadRequest, "reading body: "+err.Error())
		return nil, nil, false
	}
	defer r.Body.Close()

	sid := r.Header.Get(enclave.HeaderSessionID)
	timestamp := r.Header.Get(enclave.HeaderRequestTimestamp)
	nonce := r.Header.Get(enclave.HeaderRequestNonce)
	reqMAC := r.Header.Get(enclave.HeaderRequestMAC)

	s.mu.Lock()
	activeID := s.sessionID
	authKey := copyBytes(s.requestAuthKey)
	expiresAt := s.expiresAt
	hasActiveSession := s.sessionKey != nil && len(s.requestAuthKey) > 0 && time.Now().Before(s.expiresAt)
	s.mu.Unlock()
	defer zeroBytes(authKey)

	if !hasActiveSession {
		writeErr(w, http.StatusPreconditionFailed, "no active session")
		return nil, nil, false
	}
	if sid == "" {
		writeErr(w, http.StatusUnauthorized, "missing session")
		return nil, nil, false
	}
	if sid != activeID {
		writeErr(w, http.StatusUnauthorized, "invalid session")
		return nil, nil, false
	}
	if timestamp == "" || nonce == "" || reqMAC == "" {
		writeErr(w, http.StatusUnauthorized, "missing request authentication")
		return nil, nil, false
	}

	requestTime, err := time.Parse(time.RFC3339, timestamp)
	if err != nil {
		writeErr(w, http.StatusUnauthorized, "invalid request timestamp")
		return nil, nil, false
	}
	now := time.Now()
	if requestTime.Before(now.Add(-requestAuthMaxSkew)) || requestTime.After(now.Add(requestAuthMaxSkew)) || requestTime.After(expiresAt) {
		writeErr(w, http.StatusUnauthorized, "stale request")
		return nil, nil, false
	}
	if !enclave.VerifyRequestMAC(authKey, r.Method, r.URL.Path, body, sid, timestamp, nonce, reqMAC) {
		writeErr(w, http.StatusUnauthorized, "invalid request authentication")
		return nil, nil, false
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	if s.sessionID != sid || s.sessionKey == nil || time.Now().After(s.expiresAt) {
		writeErr(w, http.StatusPreconditionFailed, "no active session")
		return nil, nil, false
	}
	pruneSeenNonces(s.seenNonces, now.Add(-requestAuthMaxSkew))
	if _, ok := s.seenNonces[nonce]; ok {
		writeErr(w, http.StatusUnauthorized, "replayed request")
		return nil, nil, false
	}
	s.seenNonces[nonce] = now
	return body, copyBytes(authKey), true
}

func pruneSeenNonces(seen map[string]time.Time, before time.Time) {
	for nonce, seenAt := range seen {
		if seenAt.Before(before) {
			delete(seen, nonce)
		}
	}
}

// resolveConnectorID splits "type/provider" into its components.
func resolveConnectorID(id string) (string, string) {
	for i, c := range id {
		if c == '/' {
			return id[:i], id[i+1:]
		}
	}
	return id, ""
}

func decodeJSON(r *http.Request, v any) error {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		return fmt.Errorf("reading body: %w", err)
	}
	defer r.Body.Close()
	return json.Unmarshal(body, v)
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v)
}

func writeErr(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}

func writeEscrowErr(w http.ResponseWriter, err error) {
	status := http.StatusNotFound
	if err == enclave.ErrEscrowScopeMismatch {
		status = http.StatusForbidden
	}
	writeErr(w, status, err.Error())
}

func zeroBytes(b []byte) {
	for i := range b {
		b[i] = 0
	}
}

func copyBytes(b []byte) []byte {
	if b == nil {
		return nil
	}
	c := make([]byte, len(b))
	copy(c, b)
	return c
}
