package launch

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	// wrapperDirName is the directory under $HOME where the wrapper lives.
	wrapperDirName = ".aileron"
	// wrapperFileName is chosen so the full path contains "bash", which
	// satisfies Claude Code's shell-name validation.
	wrapperFileName = "bash"
)

// wrapperScript returns the contents of the wrapper shell script.
// The script receives the same args Claude Code passes to a shell
// (-c, -l, command string) and delegates to aileron-sh for policy
// evaluation before exec'ing /bin/bash.
func wrapperScript(shimPath string) string {
	return fmt.Sprintf(`#!/bin/bash
# Aileron shell wrapper — delegates to aileron-sh for policy enforcement.
# Named "bash" so that Claude Code accepts the path as a valid shell.
# Do not edit; regenerated by aileron launch.
exec %q "$@"
`, shimPath)
}

// InstallWrapper writes a bash wrapper script to ~/.aileron/bash that
// delegates to the given aileron-sh binary. Returns the absolute path
// to the installed wrapper.
func InstallWrapper(shimPath string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determining home directory: %w", err)
	}

	dir := filepath.Join(home, wrapperDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("creating wrapper directory %s: %w", dir, err)
	}

	wrapperPath := filepath.Join(dir, wrapperFileName)
	content := wrapperScript(shimPath)

	if err := os.WriteFile(wrapperPath, []byte(content), 0o755); err != nil {
		return "", fmt.Errorf("writing wrapper script %s: %w", wrapperPath, err)
	}

	return wrapperPath, nil
}
