package container

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// ToolsLockComment documents the managed-toolchain lockfile for anyone who opens
// it and is emitted as the leading "_comment" field by FormatToolsLock. The
// generator (internal/tools/toolslock) and the committed tools.lock.json share
// this single source of truth so a regenerate with no version change is a no-op
// diff.
const ToolsLockComment = "Generated by `task generate:tools-lock`. Pins the Node.js version and per-platform sha256 checksums Aileron's managed-toolchain devcontainer build (#1525) installs, so a build is reproducible and a tampered or drifted distribution archive is rejected at fetch time. The version pin lives alongside the @devcontainers/cli pin in runtime.go. Checksums are the bare lowercase hex sha256 Node publishes in its signed SHASUMS256.txt, keyed by the Node distribution platform token (e.g. darwin-arm64, linux-x64, win-x64). Unlike the agent-images lock, the Node toolchain has no floating fallback: a version pin with no checksums is rejected. Do not hand-edit; regenerate. See docs/development/sandbox-agent-images.md."

// toolsLock is the committed managed-toolchain lockfile, embedded into the
// binary. `task generate:tools-lock` regenerates it (see
// internal/tools/toolslock). It records the pinned Node.js version and, per
// supported platform, the sha256 of that platform's distribution archive so the
// managed-toolchain build (#1525) is reproducible and rejects a tampered or
// drifted archive at fetch time.
//
//go:embed tools.lock.json
var toolsLock []byte

// nodeToolsLock is the on-disk shape of the node section of tools.lock.json.
// Version is the pinned Node.js version (e.g. "22.14.0"). Checksums maps a Node
// distribution platform token (e.g. "darwin-arm64", "linux-x64", "win-x64") to
// the bare lowercase hex sha256 of that platform's distribution archive.
type nodeToolsLock struct {
	Version   string            `json:"version"`
	Checksums map[string]string `json:"checksums"`
}

// toolsLockfile is the on-disk shape of tools.lock.json. The leading "_comment"
// field in the file is ignored on decode.
type toolsLockfile struct {
	Node nodeToolsLock `json:"node"`
}

// pinnedNode is the parsed lockfile, loaded once at package init. A malformed
// committed lockfile is a build-time bug, so parsing panics rather than silently
// dropping the pin; toolslock_test.go guards the embedded file parses.
var pinnedNode = mustParseToolsLock(toolsLock)

func mustParseToolsLock(b []byte) nodeToolsLock {
	node, err := parseToolsLock(b)
	if err != nil {
		panic(fmt.Sprintf("container: malformed embedded tools.lock.json: %v", err))
	}
	return node
}

// parseToolsLock decodes a managed-toolchain lockfile into its node pin. The
// Node toolchain has no floating fallback (unlike the agent-images lock, where
// an empty map means "track latest"), so a missing version or an empty checksum
// map is a content error and is rejected. Each checksum must be a 64-char
// lowercase hex sha256 (the bare form Node ships in SHASUMS256.txt, with no
// "sha256:" prefix); a malformed entry is rejected.
func parseToolsLock(b []byte) (nodeToolsLock, error) {
	var lf toolsLockfile
	if err := json.Unmarshal(b, &lf); err != nil {
		return nodeToolsLock{}, err
	}
	version := strings.TrimSpace(lf.Node.Version)
	if version == "" {
		return nodeToolsLock{}, fmt.Errorf("node.version is empty; the managed toolchain must be pinned")
	}
	if len(lf.Node.Checksums) == 0 {
		return nodeToolsLock{}, fmt.Errorf("node %q: no checksums recorded; the managed toolchain has no floating fallback and must pin every supported platform", version)
	}
	checksums := make(map[string]string, len(lf.Node.Checksums))
	for platform, sum := range lf.Node.Checksums {
		s := strings.TrimSpace(sum)
		if !isHexSHA256(s) {
			return nodeToolsLock{}, fmt.Errorf("node %q platform %q: checksum %q is not a 64-char lowercase hex sha256", version, platform, sum)
		}
		checksums[platform] = s
	}
	return nodeToolsLock{Version: version, Checksums: checksums}, nil
}

// isHexSHA256 reports whether s is a 64-character lowercase hex string — the bare
// sha256 form Node publishes in SHASUMS256.txt.
func isHexSHA256(s string) bool {
	if len(s) != 64 {
		return false
	}
	for _, c := range s {
		switch {
		case c >= '0' && c <= '9':
		case c >= 'a' && c <= 'f':
		default:
			return false
		}
	}
	return true
}

// FormatToolsLock renders the canonical JSON for a managed-toolchain lockfile
// from a Node version and a platform->sha256 map. Output is deterministic — the
// checksum map keys are emitted sorted, so identical inputs yield byte-identical
// bytes — and round-trips through parseToolsLock. The generator writes this; a
// test asserts the committed tools.lock.json equals it, so the file can never
// drift from canonical form.
func FormatToolsLock(version string, checksums map[string]string) ([]byte, error) {
	type nodeOut struct {
		Version   string            `json:"version"`
		Checksums map[string]string `json:"checksums"`
	}
	type lockfileOut struct {
		Comment string  `json:"_comment"`
		Node    nodeOut `json:"node"`
	}
	norm := make(map[string]string, len(checksums))
	keys := make([]string, 0, len(checksums))
	for k := range checksums {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		norm[k] = strings.TrimSpace(checksums[k])
	}
	out := lockfileOut{
		Comment: ToolsLockComment,
		Node:    nodeOut{Version: strings.TrimSpace(version), Checksums: norm},
	}
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// PinnedNodeVersion returns the Node.js version pinned in the committed
// tools.lock.json (e.g. "22.14.0"). It is the single source of truth the
// managed-toolchain provisioner (internal/sandbox/toolchain, #1525) reads so the
// fetched Node version always matches the version the checksums are pinned for.
func PinnedNodeVersion() string {
	return pinnedNode.Version
}

// nodePlatformToken maps a Go GOOS/GOARCH pair to the Node distribution platform
// token used in SHASUMS256.txt (and in the checksum map). It returns ok=false for
// an OS/arch combination the managed toolchain does not support, so callers
// degrade rather than panic.
func nodePlatformToken(goos, goarch string) (string, bool) {
	var os string
	switch goos {
	case "darwin":
		os = "darwin"
	case "linux":
		os = "linux"
	case "windows":
		os = "win"
	default:
		return "", false
	}
	var arch string
	switch goarch {
	case "amd64":
		arch = "x64"
	case "arm64":
		arch = "arm64"
	default:
		return "", false
	}
	return os + "-" + arch, true
}

// pinnedNodeChecksum returns the recorded sha256 for the requested Node version
// on the given GOOS/GOARCH and whether a pin applies. ok is false when version
// is not the pinned version, when the GOOS/GOARCH pair is unsupported, or when no
// checksum is recorded for the resolved platform.
func pinnedNodeChecksum(version, goos, goarch string) (string, bool) {
	if strings.TrimSpace(version) != pinnedNode.Version {
		return "", false
	}
	token, ok := nodePlatformToken(goos, goarch)
	if !ok {
		return "", false
	}
	sum, ok := pinnedNode.Checksums[token]
	return sum, ok
}

// VerifyNodeChecksum checks a freshly-fetched Node distribution's actual sha256
// against the committed pin for version on the given GOOS/GOARCH. It returns nil
// when the pin exists and actualSHA matches, and an actionable error otherwise:
// when no pin exists for the platform (so a reviewer regenerates the lock), and
// when actualSHA disagrees with the pin (a reproducible-build failure: either a
// tampered distribution or a stale lock). This is the regression guard the
// managed-toolchain fetcher (#1525, sub-issue 4) calls at the network boundary.
func VerifyNodeChecksum(version, goos, goarch, actualSHA string) error {
	expected, ok := pinnedNodeChecksum(version, goos, goarch)
	if !ok {
		token, mapped := nodePlatformToken(goos, goarch)
		if !mapped {
			return fmt.Errorf("node %s: unsupported platform %s/%s; the managed toolchain pins no checksum for it", version, goos, goarch)
		}
		if version != pinnedNode.Version {
			return fmt.Errorf("node %s (%s): tools.lock.json pins node %s, not %s; regenerate with `task generate:tools-lock`", version, token, pinnedNode.Version, version)
		}
		return fmt.Errorf("node %s platform %s: no checksum pinned; regenerate with `task generate:tools-lock`", version, token)
	}
	actual := strings.TrimSpace(strings.ToLower(actualSHA))
	if actual != expected {
		token, _ := nodePlatformToken(goos, goarch)
		return fmt.Errorf("node %s (%s) checksum mismatch: distribution sha256 %s does not match the pinned %s; the distribution is tampered or the tools lock is stale (reproducible-build failure). If the upstream archive legitimately changed, regenerate with `task generate:tools-lock`", version, token, actual, expected)
	}
	return nil
}
