import { PUBLIC_API_BASE } from '$env/static/public';

export interface AttestationClaims {
	issuer: string;
	image_digest?: string;
	project_id?: string;
	hwmodel?: string;
	issued_at?: number;
	expires_at?: number;
}

export interface AttestationResult {
	verified: boolean;
	enclavePublicKey: Uint8Array;
	claims?: AttestationClaims;
}

/**
 * Verifies an enclave attestation token and extracts the enclave's ECDH
 * public key. In dev mode (token === "dev-ok"), verification is skipped.
 * In production, verifies the OIDC JWT against Google's JWKS and confirms
 * the ECDH public key is cryptographically bound to the attestation evidence.
 *
 * @param nonce - The freshness nonce from the attestation response.
 */
export async function verifyAttestation(
	token: string,
	enclavePublicKey: Uint8Array,
	expectedAudience: string,
	nonce?: Uint8Array
): Promise<AttestationResult> {
	if (token === 'dev-ok') {
		// Local TEE provider — no real attestation.
		return {
			verified: true,
			enclavePublicKey,
			claims: { issuer: 'local-dev', hwmodel: 'none' }
		};
	}

	// Production: verify Google Confidential Space OIDC JWT.
	const { verified, claims } = await verifyConfidentialSpaceJWT(
		token,
		expectedAudience,
		enclavePublicKey,
		nonce
	);
	return { verified, enclavePublicKey, claims };
}

// --- JWT verification internals ---

const EXPECTED_ISSUER = 'https://accounts.google.com';

interface JWTClaims {
	iss: string;
	exp: number;
	iat?: number;
	aud?: string;
	eat_nonce?: string[];
	hwmodel?: string;
	submods?: {
		container?: {
			image_digest?: string;
		};
		gce?: {
			project_id?: string;
		};
	};
}

interface JWK {
	kty: string;
	kid: string;
	alg?: string;
	use?: string;
	n?: string;
	e?: string;
	crv?: string;
	x?: string;
	y?: string;
}

interface JWKS {
	keys: JWK[];
}

async function verifyConfidentialSpaceJWT(
	token: string,
	expectedAudience: string,
	enclavePublicKey?: Uint8Array,
	nonce?: Uint8Array
): Promise<{ verified: boolean; claims: AttestationClaims }> {
	const parts = token.split('.');
	if (parts.length !== 3) {
		throw new Error('Invalid JWT: expected 3 parts');
	}

	// Decode header to extract key ID.
	const header: { alg: string; kid: string } = JSON.parse(base64UrlDecode(parts[0]));

	// Validate claims from the JWT payload.
	const jwtClaims: JWTClaims = JSON.parse(base64UrlDecode(parts[1]));

	if (jwtClaims.iss !== EXPECTED_ISSUER) {
		throw new Error(`Unexpected issuer: ${jwtClaims.iss}`);
	}

	const now = Math.floor(Date.now() / 1000);
	if (jwtClaims.exp < now) {
		throw new Error('Token expired');
	}

	// Verify JWT signature using JWKS fetched from our proxy endpoint.
	const jwks = await fetchJWKS();
	const jwk = jwks.keys.find((k) => k.kid === header.kid);
	if (!jwk) {
		throw new Error(`Signing key ${header.kid} not found in JWKS`);
	}

	const signingInput = new TextEncoder().encode(parts[0] + '.' + parts[1]);
	const signature = base64UrlToBytes(parts[2]);
	const key = await importKey(jwk, header.alg);

	const algorithm = getVerifyAlgorithm(header.alg);
	const valid = await crypto.subtle.verify(
		algorithm,
		key,
		(signature as Uint8Array<ArrayBuffer>).buffer,
		(signingInput as Uint8Array<ArrayBuffer>).buffer
	);
	if (!valid) {
		throw new Error('JWT signature verification failed');
	}

	// Post-signature checks: these claims are now trusted since the
	// signature is verified against Google's JWKS.

	// Validate audience — if the token includes an aud claim, it must match.
	if (expectedAudience && jwtClaims.aud && jwtClaims.aud !== expectedAudience) {
		throw new Error(`Unexpected audience: ${jwtClaims.aud}`);
	}

	// Validate freshness nonce is present in eat_nonce.
	if (nonce && nonce.length > 0) {
		const nonceB64 = bytesToBase64Url(nonce);
		if (!jwtClaims.eat_nonce || !jwtClaims.eat_nonce.includes(nonceB64)) {
			throw new Error('Freshness nonce not found in attestation token');
		}
	}

	// Validate ECDH public key binding: SHA-256(pubkey) must be in eat_nonce.
	// This proves the public key was generated by the attested enclave —
	// a compromised host cannot substitute a different key without breaking
	// this check.
	if (enclavePublicKey && enclavePublicKey.length > 0 && jwtClaims.eat_nonce && jwtClaims.eat_nonce.length > 0) {
		const pubkeyHash = new Uint8Array(
			await crypto.subtle.digest('SHA-256', enclavePublicKey)
		);
		const pubkeyNonce = bytesToBase64Url(pubkeyHash);
		if (!jwtClaims.eat_nonce.includes(pubkeyNonce)) {
			throw new Error(
				'ECDH public key is not bound to attestation evidence — possible host-path substitution'
			);
		}
	}

	const attestationClaims: AttestationClaims = {
		issuer: jwtClaims.iss,
		image_digest: jwtClaims.submods?.container?.image_digest,
		project_id: jwtClaims.submods?.gce?.project_id,
		hwmodel: jwtClaims.hwmodel,
		issued_at: jwtClaims.iat,
		expires_at: jwtClaims.exp
	};

	return { verified: true, claims: attestationClaims };
}

/**
 * Fetches the JWKS from the API server's proxy endpoint.
 * The server caches upstream responses for 1 hour.
 */
async function fetchJWKS(): Promise<JWKS> {
	const resp = await fetch(`${PUBLIC_API_BASE}/v1/tee/jwks`);
	if (!resp.ok) {
		throw new Error(`Failed to fetch JWKS: ${resp.status} ${resp.statusText}`);
	}
	return resp.json();
}

/**
 * Imports a JWK as a CryptoKey for signature verification.
 */
async function importKey(jwk: JWK, alg: string): Promise<CryptoKey> {
	const algorithm = getImportAlgorithm(alg);
	return crypto.subtle.importKey('jwk', jwk as JsonWebKey, algorithm, false, ['verify']);
}

function getImportAlgorithm(alg: string): RsaHashedImportParams | EcKeyImportParams {
	switch (alg) {
		case 'RS256':
			return { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' };
		case 'ES256':
			return { name: 'ECDSA', namedCurve: 'P-256' };
		default:
			throw new Error(`Unsupported algorithm: ${alg}`);
	}
}

function getVerifyAlgorithm(alg: string): AlgorithmIdentifier | RsaPssParams | EcdsaParams {
	switch (alg) {
		case 'RS256':
			return { name: 'RSASSA-PKCS1-v1_5' };
		case 'ES256':
			return { name: 'ECDSA', hash: 'SHA-256' };
		default:
			throw new Error(`Unsupported algorithm: ${alg}`);
	}
}

// --- Base64url helpers ---

function base64UrlDecode(str: string): string {
	const padded = str.replace(/-/g, '+').replace(/_/g, '/');
	return atob(padded);
}

function base64UrlToBytes(str: string): Uint8Array {
	const binary = base64UrlDecode(str);
	const bytes = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i++) {
		bytes[i] = binary.charCodeAt(i);
	}
	return bytes;
}

function bytesToBase64Url(bytes: Uint8Array): string {
	const binary = String.fromCharCode(...bytes);
	return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
