package composition

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// LockfileComment documents the digest lockfile for anyone who opens it and is
// emitted as the leading "_comment" field by FormatAgentImageLock. The generator
// (internal/tools/agentdigests) and the committed agent-images.lock.json share
// this single source of truth so a regenerate with no registry change is a
// no-op diff.
const LockfileComment = "Generated by `task generate:agent-digests` at release prep. Maps each published agent to the immutable image digest a release pulls instead of the floating `latest` tag, so a release's sandbox is reproducible and cannot drift when the freshness watcher (#1088) republishes images. An empty `images` map means no agent is pinned yet and releases keep pulling `latest` (the pre-#1233 behavior). Do not hand-edit; regenerate. See docs/development/sandbox-agent-images.md."

// agentImagesLock is the committed digest lockfile, embedded into the binary.
// `task generate:agent-digests` regenerates it at release prep (see
// internal/tools/agentdigests). It records, per published agent, the immutable
// image digest a release pulls instead of the floating `latest` tag so a
// release's sandbox is reproducible and cannot drift when the freshness watcher
// (#1088) republishes images (#1233).
//
//go:embed agent-images.lock.json
var agentImagesLock []byte

// agentImageLockfile is the on-disk shape of agent-images.lock.json. Images maps
// an agent id (e.g. "claude") to a pinned image digest ("sha256:..."). The
// leading "_comment" field in the file is ignored on decode.
type agentImageLockfile struct {
	Images map[string]string `json:"images"`
}

// pinnedAgentDigests is the parsed lockfile, loaded once at package init. A
// malformed committed lockfile is a build-time bug, so parsing panics rather
// than silently dropping pins; digests_test.go guards the embedded file parses.
var pinnedAgentDigests = mustParseAgentImageLock(agentImagesLock)

func mustParseAgentImageLock(b []byte) map[string]string {
	images, err := parseAgentImageLock(b)
	if err != nil {
		panic(fmt.Sprintf("composition: malformed embedded agent-images.lock.json: %v", err))
	}
	return images
}

// parseAgentImageLock decodes a digest lockfile into its agent->digest map. It
// returns an empty (non-nil) map when the file records no pins. Each recorded
// digest must be a "sha256:<hex>" reference; a malformed entry is a content
// error the generator should never emit, so parsing rejects it.
func parseAgentImageLock(b []byte) (map[string]string, error) {
	var lf agentImageLockfile
	if err := json.Unmarshal(b, &lf); err != nil {
		return nil, err
	}
	out := make(map[string]string, len(lf.Images))
	for agent, digest := range lf.Images {
		d := strings.TrimSpace(digest)
		if !strings.HasPrefix(d, "sha256:") || len(d) <= len("sha256:") {
			return nil, fmt.Errorf("agent %q: digest %q is not a sha256 reference", agent, digest)
		}
		out[agent] = d
	}
	return out, nil
}

// FormatAgentImageLock renders the canonical JSON for a digest lockfile from an
// agent->digest map. Output is deterministic — map keys are emitted sorted, so
// identical inputs yield byte-identical bytes — and round-trips through
// parseAgentImageLock. The generator writes this; a test asserts the committed
// agent-images.lock.json equals it, so the file can never drift from canonical
// form.
func FormatAgentImageLock(images map[string]string) ([]byte, error) {
	type lockfileOut struct {
		Comment string            `json:"_comment"`
		Images  map[string]string `json:"images"`
	}
	norm := make(map[string]string, len(images))
	keys := make([]string, 0, len(images))
	for k := range images {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		norm[k] = strings.TrimSpace(images[k])
	}
	data, err := json.MarshalIndent(lockfileOut{Comment: LockfileComment, Images: norm}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// pinnedDigest returns the recorded image digest for agent and whether a digest
// pin applies. A pin applies only to a release build: any real version maps via
// imageTag to "latest", whereas a dev or empty version maps to "edge" and is
// never pinned, preserving the invariant that dev builds track the tip. When no digest
// is recorded for the agent (the lockfile is empty until the first pinned
// release), the caller falls back to the floating `latest` tag — the pre-#1233
// behavior.
func pinnedDigest(agent, version string) (string, bool) {
	if imageTag(version) != "latest" {
		return "", false
	}
	d, ok := pinnedAgentDigests[agent]
	return d, ok
}
