package composition

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// DefaultAgent is the agent whose Feature the scaffold demonstrates. It is no
// longer selectable from the CLI; `aileron sandbox init` always emits the
// Claude Feature as the worked example of the compose model, and customers
// swap or add Feature references by hand. Claude Code and Codex have published
// agent Features today (see docs/development/sandbox-agent-images.md).
const DefaultAgent = "claude"

// InitOptions configures the sandbox scaffold operation.
type InitOptions struct {
	WorkDir string
	Version string
	Force   bool
}

// InitResult reports which files were written.
type InitResult struct {
	DevcontainerPath string
}

// Init writes the starter devcontainer scaffold for sandbox composition. The
// scaffold composes the Aileron base image with a per-agent Feature, which is
// the Tier 1 customization model recorded in ADR-0017. It no longer writes a
// per-agent Dockerfile; the zero-build per-agent-image flow is owned by #965.
func Init(opts InitOptions) (InitResult, error) {
	workDir := opts.WorkDir
	if workDir == "" {
		workDir = "."
	}
	dir := filepath.Join(workDir, ".devcontainer")
	devcontainerPath := filepath.Join(workDir, DefaultDevcontainerPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return InitResult{}, fmt.Errorf("create %s: %w", dir, err)
	}
	if _, err := os.Stat(devcontainerPath); err == nil && !opts.Force {
		return InitResult{}, fmt.Errorf("%s already exists (use --force to overwrite)", devcontainerPath)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return InitResult{}, fmt.Errorf("stat %s: %w", devcontainerPath, err)
	}
	if err := os.WriteFile(devcontainerPath, []byte(starterDevcontainer(opts.Version)), 0o644); err != nil {
		return InitResult{}, fmt.Errorf("write %s: %w", devcontainerPath, err)
	}
	return InitResult{DevcontainerPath: DefaultDevcontainerPath}, nil
}

// FeatureReference returns the canonical devcontainer Feature reference for an
// agent (e.g. "ghcr.io/alrubinger/aileron-features/claude:0"). It is the one
// place in Go that names the Feature registry path and tag, mirroring the
// BaseImage helper for the base image. The same reference identifies the
// Features authored under images/sandbox-features/<agent>/ and composed by the
// Tier 1 build path (#1083).
//
// The tag is ":0", the broadest in-house major tag. A "0.0.1" Feature manifest
// publishes the tag set "0.0.1", "0.0", "0", and "latest" through
// `devcontainer features publish`, so pinning ":0" lets 0.0.x patch bumps
// resolve without re-scaffolding. The scaffold stays on the major tag while the
// manifest holds the 0.0.x house version, keeping the two consistent without
// hard-coding a premature 1.0.0.
func FeatureReference(agent string) string {
	return DefaultFeatureRepository + "/" + agent + ":0"
}

// PublishedAgentImage returns the prebuilt per-agent sandbox image reference for
// an agent (e.g. "ghcr.io/alrubinger/aileron-sandbox-claude:latest"). It is the
// one place in Go that names the per-agent image registry path and tag,
// mirroring BaseImage for the base image. These images bake the agent CLI and
// aileron-mcp onto the base, so the build-free Tier 0 default pulls one instead
// of building the agent-less base (#1086, #1087).
//
// The reference resolves in two ways (#1233):
//   - A release build (a real version, which imageTag maps to `latest`) pulls a
//     fixed digest when the embedded lockfile records one for the agent:
//     "<repo>-<agent>@sha256:...". This makes a release's sandbox reproducible
//     and immune to drift when the freshness watcher (#1088) republishes images.
//   - Otherwise it pulls a floating tag (see imageTag): a dev or empty version
//     pulls `edge` (the tip published off main on workflow_dispatch) and is
//     never pinned, and a release with no recorded digest falls back to `latest`
//     (the pre-#1233 behavior, kept until `task generate:agent-digests` records
//     a pin at release prep). `latest` moves only on a v* tag build, so it
//     always names the most recent release.
//
// Pins live in the committed agent-images.lock.json, regenerated by
// `task generate:agent-digests` (see internal/tools/agentdigests and pinnedDigest).
func PublishedAgentImage(agent, version string) string {
	if digest, ok := pinnedDigest(agent, version); ok {
		return DefaultPublishedImageRepository + "-" + agent + "@" + digest
	}
	return DefaultPublishedImageRepository + "-" + agent + ":" + imageTag(version)
}

// LocalAgentImageTag returns the local-only image tag for a recipe'd-but-not-
// publishable agent built from a synthesized devcontainer (#1451). The name is
// deterministic per (agent, image tag) so the `auto` build policy can skip a
// rebuild when the image already exists locally. It is never pushed to a
// registry — the "aileron/" prefix (no registry host) keeps it a local-daemon
// tag, mirroring ProjectImageTag's convention.
func LocalAgentImageTag(agent, version string) string {
	return "aileron/sandbox-agent-" + agent + ":" + imageTag(version)
}

// PublishedAgents returns the agents whose per-agent image is publishable, i.e.
// whose CLI license permits Aileron to bake it into a redistributable image and
// host it on GHCR (see agentPublishable). It is the single source of truth for
// "which images exist to publish" consumed by the digest-pin generator
// (internal/tools/agentdigests) and the sandbox-agents CI matrix, so a
// publishable agent is automatically pinned at release prep and a
// non-publishable one (e.g. Claude Code) is auto-excluded from publishing
// without further wiring (#1451). The list is sorted for determinism.
func PublishedAgents() []string {
	agents := make([]string, 0, len(agentRecipes))
	for agent, recipe := range agentRecipes {
		if recipe.Publishable {
			agents = append(agents, agent)
		}
	}
	sort.Strings(agents)
	return agents
}

// PublishedAgentExists reports whether agent ships a prebuilt, publishable
// per-agent image to pull for the build-free default. It is the publish-eligible
// subset of recipe-existence: an agent must both have a verified recipe AND have
// a redistributable CLI license (see agentPublishable). Discover and `sandbox
// check` share this predicate so both resolve the same published image (the
// launch/check parity requirement). A recipe'd-but-not-publishable agent (e.g.
// Claude Code) is false here and resolves to a LOCAL Feature build instead of a
// published image pull (#1451).
func PublishedAgentExists(agent string) bool {
	return agentPublishable(agent)
}

// synthesizedAgentDevcontainer returns the devcontainer.json that composes the
// Aileron base image with a single agent Feature, used by Discover's
// no-.devcontainer local-build branch for a recipe'd-but-not-publishable agent
// (e.g. Claude Code). It carries no commented customer-tooling slot and no
// customizations block: it is a build-only artifact materialized into a managed
// temp workspace folder by the container builder, never written into the user's
// workDir (#1451). The Aileron customizations the launcher needs (mediation,
// approval surface, credential sealing) are applied runtime-side regardless of
// image provenance, so this minimal config is sufficient to build a launchable
// agent image.
func synthesizedAgentDevcontainer(agent, version string) string {
	return fmt.Sprintf(`{
  "name": "Aileron sandbox",
  "image": %q,
  "features": {
    %q: {}
  }
}
`, BaseImage(version), FeatureReference(agent))
}

// starterDevcontainer emits the Feature-composing devcontainer.json recorded in
// docs/development/sandbox-composition.md. It composes the Aileron base image
// with the default agent Feature and demonstrates the customer-tooling slot as
// a commented Feature so `Discover` parses exactly one active Feature. JSONC
// comments are valid here because Discover strips them before parsing.
func starterDevcontainer(version string) string {
	return fmt.Sprintf(`{
  "name": "Aileron sandbox",
  "image": %q,
  "features": {
    // The agent Feature installs the agent CLI onto the base image. Swap
    // "claude" for another published agent (e.g. "codex"), or list several.
    %q: {}
    // Add your own tooling as its own Feature alongside the agent Feature:
    // "ghcr.io/acme/internal-tools:1": {}
  },
  "customizations": {
    "aileron": {
      "mediation": "default",
      "approval_surface": "both"
    }
  }
}
`, BaseImage(version), FeatureReference(DefaultAgent))
}
